
supportops_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: supportops
      password: supportops
      port: 5432
      dbname: supportops
      schema: mart
      threads: 1